apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dapr-operator
  namespace: dapr-system
spec:
  interval: 1m0s
  url: https://dapr.github.io/helm-charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dapr-operator
  namespace: dapr-system
spec:
  chart:
    spec:
      chart: dapr/dapr
      sourceRef:
        kind: HelmRepository
        name: dapr-operator
        namespace: flux-system
      version: 1.7
  interval: 5m